server:
  port: ${PORT:8000}
spring:
  cloud:
    stream:
      bindings:
        input: players
spring:
  cloud:
    stream:
      bindings:
        input:
          group: players
spring:
  cloud:
    stream:
      bindings:
        input:
          durableSubscription = true
just:
  a:
    test: my test property
